services:
  prunedash:
    build:
      context: ./backend
      dockerfile: Dockerfile
    privileged: true
    pid: host
    ports:
      - "3333:3333"
    volumes:
      - /var/cache/pacman/pkg:/host/var/cache/pacman/pkg:rw
      - /var/log/journal:/host/var/log/journal:rw
      - /home/nui/.cache:/host/home/nui/.cache:rw
      - /home/nui/.config:/host/home/nui/.config:ro
      - /home/nui/.prune:/host/home/nui/.prune:rw
    environment:
      - NODE_ENV=development
    restart: always
