services:
  prunedash:
    build:
      context: ./backend
      dockerfile: Dockerfile
    privileged: true
    pid: host
    ports:
      - "3333:3333"
    volumes:
      - /var/cache/pacman/pkg:/host/var/cache/pacman/pkg:rw
      - /var/log/journal:/host/var/log/journal:rw
      - /home/nui/.cache:/host/home/nui/.cache:rw
      - /home/nui/.config:/host/home/nui/.config:ro
      - /home/nui/.prune:/host/home/nui/.prune:rw
      - /home/nui/.local/share/themes:/host/home/nui/.local/share/themes:rw
      - /home/nui/.local/share/icons:/host/home/nui/.local/share/icons:rw
      - /home/nui/.local/share/fonts:/host/home/nui/.local/share/fonts:rw
      - /home/nui/.themes:/host/home/nui/.themes:rw
      - /home/nui/.icons:/host/home/nui/.icons:rw
      - /home/nui/.fonts:/host/home/nui/.fonts:rw
      - /usr/share/themes:/host/usr/share/themes:rw
      - /usr/share/icons:/host/usr/share/icons:rw
      - /usr/share/fonts:/host/usr/share/fonts:rw
      - /usr/share/sddm/themes:/host/usr/share/sddm/themes:rw
      - /etc/sddm.conf:/host/etc/sddm.conf:ro
      - /etc/sddm.conf.d:/host/etc/sddm.conf.d:ro
    environment:
      - NODE_ENV=development
    restart: always
